jobs:
  include:
    - stage: build
      name: build
      dist: bionic
      language: minimal
      script:
        - make pull-builder
        - make oi-binaries
    - stage: test
      name: unit and integration tests
      dist: bionic
      language: minimal
      script:
        - make pull-builder
        - make test
    - name: e2e tests with local CRI endpoints
      dist: bionic
      language: minimal
      script:
        - make deps
        - make e2e
    - name: e2e tests with remote CRI endpoints
      dist: bionic
      language: minimal
      script:
        - make deps
        - make e2e-remote
